### ISSUE TITLE
Blazor WASM NullReferenceException

### ISSUE THREAD

**Issue by jameswoodley** [zzzprojects/System.Linq.Dynamic.Core#504] opened 2021-05-06 19:32 UTC
## 1. Description
When attempting to run a simple query on a collection in Blazor, getting a NullReferenceException. The exact same query, on the exact same dataset, works perfectly in the Unit Tests, however when running in the browser you get the error
![image](https://user-images.githubusercontent.com/52610563/117354894-cbfd1900-aea9-11eb-9eb6-146f248f62ce.png)

## 2. Exception
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: Arg_NullReferenceException
System.NullReferenceException: Arg_NullReferenceException
at System.Linq.Dynamic.Core.Parser.KeywordsHelper..ctor(ParsingConfig config)
at System.Linq.Dynamic.Core.Parser.ExpressionParser..ctor(ParameterExpression[] parameters, String expression, Object[] values, ParsingConfig parsingConfig)
at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values)
at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Any(IQueryable source, ParsingConfig config, String predicate, Object[] args)
at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Any(IQueryable source, String predicate, Object[] args)
```

See attachments for data sets, and try the following code:
``` c#
[Fact]
public async Task Should_Work_With_Real_World_Values()
{
    // Arrange
    var formData = await File.ReadAllTextAsync("FormElement/form_data.json");
    var formElementData = await File.ReadAllTextAsync("FormElement/form_elements.json");
    var dataContext = JsonConvert.DeserializeObject<Dictionary<string, FormValue<string>>>(formData);
    var formElements = JsonConvert.DeserializeObject<FormElementReadModel[]>(formElementData);
    
    // Act
    var groupedElements = formElements
        .Where(element => element.Page == 2)
        .Where(element => dataContext.Values.AsQueryable()
            .Any(string.IsNullOrEmpty(element.InclusionRule) ? "true == true" : element.InclusionRule))
        .GroupBy(element => element.Group)
        .Select(group => new GroupedFormElements
        {
            Legend = group.Key ?? string.Empty,
            Elements = group.ToArray()
        }).ToArray();
    
    // Assert
    groupedElements.Any().ShouldBeTrue();
}
```

I've even tried the following code to take any of the dynamic elements out of the equation:
``` c#
_groupedFormElements = _form.Elements
        .Where(element => element.Page == CurrentPage)
        .Where(element => _dataContext.Values.AsQueryable().Any("true == true"))
        .GroupBy(element => element.Group)
        .Select(group => new GroupedFormElements
        {
            Legend = group.Key ?? string.Empty,
            Elements = group.ToArray()
        }).ToArray();
```
but the same error persists.

As I say, only in Blazor. I have followed the documentation and do have
![image](https://user-images.githubusercontent.com/52610563/117355065-fea71180-aea9-11eb-8ff3-1a8ec3622cc4.png)
in the .csproj file

Any help would be gratefully appreciated

[form_elements.zip](https://github.com/zzzprojects/System.Linq.Dynamic.Core/files/6437159/form_elements.zip)

**Comment by StefH** [comment] 2021-05-06 20:08
@jameswoodley 

Can you please fork this project, and add your failing to"src-blazor/BlazorWASMExample" application I just created? And then make a PR so that I can analyse your code.

**Comment by jameswoodley** [comment] 2021-05-06 21:10
Think have resolved with some data analysis and null being returned from another query so lets close this for now. I don't want to waste your time.

Thanks for replying however!

**Comment by jomalbert1594** [comment] 2022-11-21 08:37
@jameswoodley i'm experiencing this problem, how did you fix this?

**Comment by plachor** [comment] 2023-01-26 12:46
Hi @StefH  I believe we have similar issue. I also observer `NullReferenceException` in `KeywaordsHelper` ctor. I think this line of code is behind:

https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/CustomTypeProviders/AbstractDynamicLinqCustomTypeProvider.cs#L98

Have not spend much on analysis but this `reflectionTypeLoadException.Types` in XML comment state that they might return `null`. Additionally this is odd that for non-exception case you apply filter and for one that was retruned in excption you do not. 

Can you check this ?

**Comment by plachor** [comment] 2023-01-27 09:16
Also how this `KeywordsHelper` might be affected by this none-deterministic 3 paths:

1. happy path - out-filtered set of types from assemblies
2. partially loaded types - with possibly all types from assembly?
3. some other exception yielding no results

**Comment by plachor** [comment] 2023-02-01 06:21
@StefH  could you check those leads?

**Comment by jameswoodley** [comment] 2023-02-01 13:05
> @jameswoodley i'm experiencing this problem, how did you fix this?

Apologies for delay, what fixed it for us was that some of the elements within the collection were null. Filtering them out 1st resolved the issue.

Doesn't explain why in Blazor it fails, and not outside of Blazor, but got us through the issue we were facing at the time

**Comment by StefH** [comment] 2023-02-04 17:49
@plachor 
I've some difficulties following your leads. Can you please provide a full working Blazor WASM example which reproduces this error?

**Comment by plachor** [comment] 2023-02-04 18:04
I have observed this exception in regular net6 app deployed in kubernetes. Have you checked this line of code ? Documenting states that this list can contain null which is the case I believe. Also can you elaborate how this 3 different cases can affect this KeywordsHelper?

**Comment by StefH** [comment] 2023-02-04 18:54
> Hi @StefH I believe we have similar issue. I also observer `NullReferenceException` in `KeywaordsHelper` ctor. I think this line of code is behind:
> 
> https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/CustomTypeProviders/AbstractDynamicLinqCustomTypeProvider.cs#L98
> 
> Have not spend much on analysis but this `reflectionTypeLoadException.Types` in XML comment state that they might return `null` : https://learn.microsoft.com/en-us/dotnet/api/System.Reflection.ReflectionTypeLoadException.Types?view=net-6.0#property-value
> 
> Additionally this is odd that for non-exception case you apply filter and for one that was retruned in excption you do not.
> 
> Can you check this ?

Indeed, the Types property can have some results which are null, so I've added an extra check.
See PR
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/665

I did not look into the KeywordsHelper yet, do you expect also an error there?

**Comment by plachor** [comment] 2023-02-04 19:14
Well the outcome of this code is used there that was the reason of null reference exception. But i'm also working about not deterministic outcome. It seems this code take what ever is returned on specyfic error. Any other error yields empty result. And filtered types are returned only for  happy path. 

Like listed here https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/504#issuecomment-1406220679

**Comment by StefH** [comment] 2023-02-04 19:44
The way I see this code:
``` c#
foreach (var assembly in assemblies)
        {
            var definedTypes = Type.EmptyTypes;

            try
            {
                definedTypes = assembly
                    .GetExportedTypes()
                    .Where(t => t.IsDefined(typeof(DynamicLinqTypeAttribute), false))
                    .ToArray();
            }
            catch (ReflectionTypeLoadException reflectionTypeLoadException)
            {
                definedTypes = reflectionTypeLoadException.Types.WhereNotNull().ToArray();
            }
            catch
            {
                // Ignore all other exceptions
            }

            foreach (var definedType in definedTypes.Distinct())
            {
                yield return definedType;
            }
        }
```


1. loop all assemblies
2. for each assembly : GetExportedTypes
    if that is ok, collect the types and add these to the yield
    if that fails (ReflectionTypeLoadException), try to get the types which _are_ loaded correctly add these to the yield
    if it fails with other exception, there is an other fault with GetExportedTypes, so for this assembly, we can't use any types

This logic seems ok to me.

**Comment by plachor** [comment] 2023-02-04 19:58
1) For happy path you apply filter: Where(t => t.IsDefined(typeof(DynamicLinqTypeAttribute), false)) which you do not apply for case with error

2) Also seems this can fail on some rare conditions it happened once for us in kubernetes i cannot reproduce this but after restart it has not occured any more. I guess this was caused by parallel request to load those types or similar. In our case we use it in a singleton so if it fails it it is broken for whole lifetime of container.

**Comment by StefH** [comment] 2023-02-04 20:11
1. It's fixed now. Thanks for the code review.

2. swallow exceptions: this has been in this library since 2016, so for now I'll just keep it here.
Maybe in the future I'll add some logging for this.

**Comment by plachor** [comment] 2023-02-04 20:26
Thnx

**Closed** 2023-02-05 10:02 UTC
Labels: question
