### ISSUE TITLE
Using Max requires a cast to object

### ISSUE THREAD

**Issue by bobbymthompson** [zzzprojects/System.Linq.Dynamic.Core#169] opened 2018-05-31 19:12 UTC
Using this test code:

``` c#
NetStandardDbContext context = new NetStandardDbContext();

var typed = context.Issues
	.Where(i => context.Issues.Max(x => x.RevisionDate) == i.RevisionDate)
	.Select(i => new { i.Title, i.RevisionDate })
	.ToList();

var success = context.Issues
	.Where("@0.Max(RevisionDate) == object(RevisionDate)", context.Issues)
	.Select("new(Title, RevisionDate)")
	.ToDynamicList();

var failure = context.Issues
	.Where("@0.Max(RevisionDate) == RevisionDate", context.Issues)
	.Select("new(Title, RevisionDate)")
	.ToDynamicList();
```
Which generates:
``` sql
select title, revisiondate from issues i where (select max(revisiondate) from issues) = i.revisiondate
```

Using Max as a dynamic where clause, the following exception occurs:

System.Linq.Dynamic.Core.Exceptions.ParseException: 'Operator '==' incompatible with operand types 'Object' and 'DateTime?''

If you cast the right expression to object, the comparison succeeds. I do not believe that the left expression should be cast to object. 

I traced this to `ExpressionParser::ParseAggregate`

``` c#
Type callType = typeof(Enumerable);
if (isQueryable && MethodFinder.ContainsMethod(typeof(IQueryableSignatures), methodName, false, args))
{
     callType = typeof(Queryable);
}
```

Upon calling into this method it will change the args Type from a Nullable DateTime to an object. Stepping over this bypasses the issue.

**Comment by StefH** [comment] 2018-06-01 10:49
Quick question: do you get the same error when using `DateTime` instead a nullable `DateTime` ?

**Comment by striker8118** [comment] 2018-06-05 01:10
Yes. It doesn't matter if it is nullable or not.

**Comment by StefH** [comment] 2019-11-20 10:09
@striker8118 is this still an issue for you?

**Comment by StefH** [comment] 2023-09-10 10:15
Hello @bobbymthompson,
I'm not able to reproduce this using the latest version. I'll close this issue.

``` c#
[Fact]
public void Max_Where_On_DateTime()
{
    // Arrange
    var users = User.GenerateSampleModels(10);

    // Act
    var typed = users
        .Where(u => users.Max(m => m.BirthDate) == u.BirthDate)
        .ToList();
    var dynamic = users.AsQueryable()
        .Where("@0.Max(BirthDate) == BirthDate", users)
        .ToList();

    // Assert
    dynamic.Should().BeEquivalentTo(typed);
}

[Fact]
public void Max_Where_On_NullableDateTime()
{
    // Arrange
    var users = User.GenerateSampleModels(10);

    // Act
    var typed = users
        .Where(u => users.Max(m => m.EndDate) == u.EndDate)
        .ToList();
    var dynamic = users.AsQueryable()
        .Where("@0.Max(EndDate) == EndDate", users)
        .ToList();

    // Assert
    dynamic.Should().BeEquivalentTo(typed);
}
```

https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/744

**Closed by StefH** 2023-09-10 10:15 UTC
